const { askAI } = require("../../lib/aiHelper");

module.exports = {
    name: "code",
    aliases: ["codegen", "program", "dev"],
    description: "Generate code from a natural language prompt.",
    category: "ai",
    execute: async ({ sock, jid, args, msg }) => {
        const prompt = args.join(" ").trim();
        if (!prompt) {
            return await sock.sendMessage(jid, {
                text:
                    "💻 *Usage:* `.code <what you want to build>`\n\n" +
                    "*Examples:*\n" +
                    "• `.code a Python function to reverse a string`\n" +
                    "• `.code a JavaScript countdown timer`\n" +
                    "• `.code SQL query to get top 10 users by sales`"
            });
        }

        try {
            await sock.sendMessage(jid, { react: { text: "💻", key: msg.key } });
            await sock.sendMessage(jid, { text: "💻 Writing code... ⏳" });

            const system =
                "You are an expert software engineer. " +
                "When given a task, respond ONLY with the code and a very short explanation. " +
                "Format the code inside triple backticks with the language name. " +
                "Be concise and practical. Do not add unnecessary filler text.";

            const result = await askAI(prompt, system);

            await sock.sendMessage(jid, {
                text:
                    `💻 *CODE GENERATOR*\n\n` +
                    `📝 *Task:* ${prompt}\n\n` +
                    `━━━━━━━━━━━━━━━━\n` +
                    `${result}\n` +
                    `━━━━━━━━━━━━━━━━\n\n` +
                    `_Generated by Firebox Bot AI_`
            }, { quoted: msg });

        } catch (err) {
            console.error("Code error:", err);
            await sock.sendMessage(jid, { text: "⚠️ Code generation failed. Please try again." });
        }
    }
};
